spring:
  datasource:
    url: jdbc:h2:file:~/db/demoDB;AUTO_SERVER=TRUE;
    platform: h2
    driver-class-name: org.h2.Driver
    username: admin
    password: 0000
  h2:
    console:
      path: /h2console
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.springframework.web : error
    jy.park : debug

  pattern:
    console: "jy.park.demo1.console -- %d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"